version: '3'

services:
  appointments:
    image: shoaib1337/ams-appointments:e1d0087e5cfba28e7b0554763f6819c539cb0a3b
    ports:
      - "7071:7070"
    networks:
      - mynetwork

  doctors:
    image: shoaib1337/ams-doctors:d497df40a782243832faf4f50c0f9d87e2bbeaf8
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  frontend:
    image: shoaib1337/ams-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  db:
    image: mysql:${DB_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
