version: '3'

services:
  appointments:
    image: shoaib1337/ams-appointments:6baf75b8a59112ec3586c8a5ae1a11e8a17ff41a
    ports:
      - "7071:7070"
    networks:
      - mynetwork

  doctors:
    image: shoaib1337/ams-doctors:6baf75b8a59112ec3586c8a5ae1a11e8a17ff41a
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  frontend:
    image: shoaib1337/ams-frontend:59c3c78b9cd5355cb30093f36689a91ca0879831
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  db:
    image: mysql:${DB_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
