apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000  # my non-root user id is 1000
      initContainers:
      - name: init-ubuntu
        image: ubuntu:20.04
        command: ["/bin/sh", "-c"]
        args:
        - echo "Hello, I'm shoaib. Initiating..."; sleep 5
      containers:
      - name: frontend
        image: shoaib1337/ams-frontend
        ports:
        - containerPort: 3000
        env:
            - name: DOCTORS_SERVICE_URL
              value: doctors-service:9090
            - name: APPOINTMENTS_SERVICE_URL
              value: appointments-service:7070
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
