apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
      - name: doctors
        image: shoaib1337/ams-doctors:${DOCTORS_TAG}
        env:
          - name: APPOINTMENTS_API_URL
            value: "http://appointments-service:7070"

---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
