name: CI/CD for Appointments Microservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'appointments/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      APPOINTMENTS_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image for Appointments
        run: |
          cd doctors-appointment-system/appointments
          docker build -t shoaib1337/ams-appointments:${APPOINTMENTS_TAG} .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push shoaib1337/ams-appointments:${APPOINTMENTS_TAG}

      - name: Update Docker Compose file
        run: |
          sed -i 's|shoaib1337/ams-appointments:.*|shoaib1337/ams-appointments:${APPOINTMENTS_TAG}|' docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update Appointments image tag to ${APPOINTMENTS_TAG}"
          git push
