name: CI/CD for Doctors Microservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'doctors/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCTORS_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image for Doctors
        run: |
          cd doctors-appointment-system/doctors
          docker build -t shoaib1337/ams-doctors:${DOCTORS_TAG} .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push shoaib1337/ams-doctors:${DOCTORS_TAG}

      - name: Update Docker Compose file
        run: |
          sed -i 's|shoaib1337/ams-doctors:.*|shoaib1337/ams-doctors:${DOCTORS_TAG}|' docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update Doctors image tag to ${DOCTORS_TAG}"
          git push
