name: CI/CD for Frontend Microservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      FRONTEND_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image for Frontend
        run: |
          cd frontend
          docker build -t shoaib1337/ams-frontend:${FRONTEND_TAG} .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push shoaib1337/ams-frontend:${FRONTEND_TAG}

      - name: Update Docker Compose file
        run: |
          sed -i 's|shoaib1337/ams-frontend:.*|shoaib1337/ams-frontend:${FRONTEND_TAG}|' docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update Frontend image tag to ${FRONTEND_TAG}"
          git push
