name: CI/CD for Frontend Microservice

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      FRONTEND_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
           git config --global user.email "sali18089@gmail.com"
           git config --global user.name "shoaib-1337"

      - name: Build and push Docker image for Frontend
        run: |
          cd frontend
          docker build -t shoaib1337/ams-frontend:${FRONTEND_TAG} .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push shoaib1337/ams-frontend:${FRONTEND_TAG}

      - name: Update Docker Compose file
        run: |
            sed -i "s|shoaib1337/ams-frontend:[0-9a-f]\{40\}|shoaib1337/ams-frontend:${{ github.sha }}|g; s|shoaib1337/ams-frontend:latest|shoaib1337/ams-frontend:${{ github.sha }}|g" docker-compose.yml


      - name: Push docker-compose with new image tag
        run: |
          git config user.email "sali18089@gmail.com" 
          git config user.name "shoaib-1338"
          git add docker-compose.yml
          git commit -m "Update appointments service image tag to ${{ github.sha }}"
          git config pull.rebase true
          git pull
          git push https://${{ secrets.PAT }}@github.com/shoaib-1337/DevOps-Project.git HEAD:main