name: CI/CD for MySQL Database

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'doctors-appointment-system/mysql/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DB_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
          git config --global user.email "sali18089@gmail.com"
          git config --global user.name "shoaib-1337"

      - name: Build and push Docker image for MySQL
        run: |
          cd mysql
          docker build -t shoaib1337/ams-mysql:${DB_TAG} .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push shoaib1337/ams-mysql:${DB_TAG}

      - name: Update Docker Compose file
        run: |
          sed -i 's|shoaib1337/ams-mysql:.*|shoaib1337/ams-mysql:${DB_TAG}|' docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update MySQL image tag to ${DB_TAG}"
          git push
